### ISSUE TITLE
RFC HTTP 2 Standard durcharbeiten

### ISSUE THREAD

**Issue by tom95** [HPI-SWA-Teaching/SWT17-Project-16#3]
- [x] Dokumentation erstellen: Abbild Klassen <-> Standard
- [x] Treffen mit ehemaligen Entwicklern

3 TI-Übung

**Comment by ShirleyNekoDev** [comment]
- [x] Dokumentation übertragen ins [Wiki](https://github.com/hpi-swa-teaching/HTTP-2/wiki/RFC7540-Implementation)
